### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by jugmac00** [morepath/morepath_sqlalchemy#4]
- drop support for Python versions < 3.6
- add support for Python versions 3.7, 3.8 (if missing)
- fix linting errors (if present)

If you are a beginner, and need to help for this issue, especially during Hacktoberfest, please comment here or reach out to me via https://jugmac00.github.io/

**Comment by Aniruddha-Shriwant** [comment]
Hey @jugmac00 , I would like to work on it!

**Comment by jugmac00** [comment]
Once again, glad to have you back again.

Just go for it - the pr will already count for Hacktoberfest - be sure you have signed up.

**Comment by jugmac00** [comment]
closed by #5

**Comment by Aniruddha-Shriwant** [comment]
Hey @jugmac00 ,
I think Hacktoberfest has new rules now,
PR won't count if the repo is not participated in Hacktoberfest and in order to participate in Hacktoberfest, the maintainers should add the Hacktoberfest topic to their repo
![image](https://user-images.githubusercontent.com/58624108/94990541-9d793180-059a-11eb-9565-bc2a6f267272.png)

**Comment by jugmac00** [comment]
Hi @Aniruddha-Shriwant 
no worries. The new rules only apply to PRs after Oct 3 - the PRs until then remain valid.
